'use client';

import React from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { useAppStore } from '@/lib/store';
import { Map, Calendar } from 'lucide-react';
import TimelineHorizon from '../dashboard/TimelineHorizon';

export default function RoadmapModal() {
  const { activeModal, closeModal, project } = useAppStore();
  const isOpen = activeModal === 'roadmap-view';

  return (
    <Dialog open={isOpen} onOpenChange={(open) => { if (!open) closeModal(); }}>
      <DialogContent className="glass border-[#00F0FF]/30 bg-[#0A0E27]/95 max-w-5xl">
        <DialogHeader>
          <DialogTitle className="font-display text-2xl font-bold text-[#E8F0FF] flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-[#00F0FF]/20 border-2 border-[#00F0FF]/40 flex items-center justify-center">
              <Map className="w-5 h-5 text-[#00F0FF]" />
            </div>
            Mission Roadmap: {project?.name}
          </DialogTitle>
        </DialogHeader>

        <div className="py-6">
            <TimelineHorizon />
            
            <div className="mt-8 p-4 rounded-xl bg-[#00F0FF]/5 border border-[#00F0FF]/20">
                <h4 className="font-bold text-[#00F0FF] mb-2 flex items-center gap-2">
                    <Calendar className="w-4 h-4" />
                    Strategic Overview
                </h4>
                <p className="text-sm text-[#8B9DC3]">
                    This roadmap represents the autonomous execution plan generated by the OctoOps Agent Network. 
                    Milestones are dynamically updated based on task completion and risk assessments.
                </p>
            </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
